### ISSUE TITLE
Don't call the utility to get a shell in php-fpm container `ssh`

### ISSUE THREAD

**Issue by etherealite** [dwnload/wp-docker-bedrock#1]
the script [bin/ssh.sh](https://github.com/dwnload/wp-docker-bedrock/blob/master/bin/ssh.sh) doesn't open an ssh session, therefor calling it ssh.sh is is misnomer.  Why not avoid confusing people and call it __shell.sh__ or something to that degree?

**Comment by thefrosty** [comment]
@etherealite PRs welcome 😉
